[tools]
go = "1.24"
helm = "4"
kubectl = "1.33"
node = "24"
pnpm = "11"
python = "3.12"

# CLI tools
"npm:calldiff" = "latest"

# LSP & Formatters
rust-analyzer = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"npm:@astrojs/language-server" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:@typescript/native-preview" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"
"lua-language-server" = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["java", "node", "python", "rust"]
