return {
	-- {
	-- 	"projekt0n/github-nvim-theme",
	-- 	lazy = false,
	-- 	priority = 1000,
	-- 	name = "github-theme",
	-- 	opts = {
	-- 		options = {
	-- 			transparent = true,
	-- 			dim_inactive = false,
	-- 			hide_end_of_buffer = true,
	-- 			hide_nc_statusline = true,
	-- 			styles = {
	-- 				comments = "italic",
	-- 				keywords = "bold",
	--
	-- 			},
	-- 			darken = {
	-- 				floats = false
	-- 			},
	-- 			modules = {
	-- 				"cmp",
	-- 				"diagnostic",
	-- 				"gitsigns",
	-- 				"indent_blankline",
	-- 				"native_lsp",
	-- 				"telescope",
	-- 				"treesitter",
	-- 				"treesitter_context",
	-- 				"neogit",
	-- 			},
	-- 		},
	-- 		groups = {
	-- 			all = {
	-- 				StatusLine = { bg = 'NONE', fg = 'fg0' },
	-- 				StatusLineNC = { bg = 'NONE', fg = 'bg1', sp = 'bg0' },
	-- 				StatusLineTerm = { link = 'StatusLine' },
	-- 				StatusLineTermNC = { link = 'StatusLineNC' }
	-- 			}
	-- 		}
	-- 	},
	-- 	config = function(_, opts)
	-- 		require("github-theme").setup(opts)
	--
	-- 	end,
	-- }
}

