[tools]
aws-cli = "2"
go = "1.24"
helm = "3"
java = "temurin-21"
kubectl = "1.30"
"asdf:richin13/asdf-neovim" = "nightly"
node = "22"
oci = "3"
pnpm = "10"
python = "3.12"
rust = "1.84"
uv = "0"
yarn = "4"
zig = "0.13"

[settings]
idiomatic_version_file_enable_tools = ["python"]
